# Generated by Django 5.2.10 on 2026-01-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique genre name (e.g., Action, Drama, Comedy)",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Official title of the movie",
                        max_length=255,
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Year in which the movie was released"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Average movie rating (e.g., 8.5)",
                        max_digits=3,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the movie record was created",
                    ),
                ),
            ],
            options={
                "ordering": ["-release_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        help_text="Genre assigned to the movie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.genre",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        help_text="Movie associated with the genre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                help_text="Genres associated with this movie",
                related_name="movies",
                through="movies.MovieGenre",
                to="movies.genre",
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full legal or stage name of the person",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short biography or career summary"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Date of birth (optional)", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="movies_pers_name_64a075_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the character played by the actor",
                        max_length=255,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        help_text="Movie in which the actor appeared",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person who acted in the movie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                help_text="Actors who appeared in this movie",
                related_name="acted_movies",
                through="movies.MovieActor",
                to="movies.person",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                help_text="Director of the movie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directed_movies",
                to="movies.person",
            ),
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(
                fields=["genre", "movie"], name="movies_movi_genre_i_decaf6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviegenre",
            unique_together={("movie", "genre")},
        ),
        migrations.AddIndex(
            model_name="movieactor",
            index=models.Index(
                fields=["person", "movie"], name="movies_movi_person__5a52eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="movieactor",
            unique_together={("movie", "person")},
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_year"], name="movies_movi_release_81d5c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["title", "release_year"], name="movies_movi_title_1b2d98_idx"
            ),
        ),
    ]
