# Generated by Django 5.2.10 on 2026-01-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the movie genre (e.g., Action, Drama)",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full name of the actor",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short biography of the actor"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Actor's date of birth", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="movies_acto_name_2656bd_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full name of the director",
                        max_length=255,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief biography of the director"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="movies_dire_name_7fd370_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Title of the movie", max_length=255
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Year the movie was released"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Movie rating (e.g., 8.5)",
                        max_digits=3,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the movie was added",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        help_text="Director of the movie",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="movies.director",
                    ),
                ),
            ],
            options={
                "ordering": ["-release_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Actor involved in the movie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        help_text="Movie the actor participated in",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                help_text="Actors appearing in the movie",
                related_name="movies",
                through="movies.MovieActor",
                to="movies.actor",
            ),
        ),
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        help_text="Genre associated with this movie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.genre",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        help_text="Movie associated with this genre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                help_text="Genres associated with the movie",
                related_name="movies",
                through="movies.MovieGenre",
                to="movies.genre",
            ),
        ),
        migrations.AddIndex(
            model_name="movieactor",
            index=models.Index(
                fields=["actor", "movie"], name="movies_movi_actor_i_78b650_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="movieactor",
            unique_together={("movie", "actor")},
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(
                fields=["genre", "movie"], name="movies_movi_genre_i_decaf6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviegenre",
            unique_together={("movie", "genre")},
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_year"], name="movies_movi_release_81d5c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["director"], name="movies_movi_directo_7b63be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["title", "release_year"], name="movies_movi_title_1b2d98_idx"
            ),
        ),
    ]
