# Generated by Django 5.2.10 on 2026-01-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_add_image_urls"),
        ("movies", "0002_movie_image_url_person_image_url"),
    ]

    operations = []
